//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34209
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 5.0.61118.0
// 


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET", ConfigurationName="countrySoap")]
public interface countrySoap
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.webserviceX.NET/GetCountryByCountryCode", ReplyAction="*")]
    System.IAsyncResult BeginGetCountryByCountryCode(GetCountryByCountryCodeRequest request, System.AsyncCallback callback, object asyncState);
    
    GetCountryByCountryCodeResponse EndGetCountryByCountryCode(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.webserviceX.NET/GetISD", ReplyAction="*")]
    System.IAsyncResult BeginGetISD(GetISDRequest request, System.AsyncCallback callback, object asyncState);
    
    GetISDResponse EndGetISD(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.webserviceX.NET/GetCountries", ReplyAction="*")]
    System.IAsyncResult BeginGetCountries(GetCountriesRequest request, System.AsyncCallback callback, object asyncState);
    
    GetCountriesResponse EndGetCountries(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.webserviceX.NET/GetCurrencyCodeByCurrencyName", ReplyAction="*")]
    System.IAsyncResult BeginGetCurrencyCodeByCurrencyName(GetCurrencyCodeByCurrencyNameRequest request, System.AsyncCallback callback, object asyncState);
    
    GetCurrencyCodeByCurrencyNameResponse EndGetCurrencyCodeByCurrencyName(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.webserviceX.NET/GetISOCountryCodeByCountyName", ReplyAction="*")]
    System.IAsyncResult BeginGetISOCountryCodeByCountyName(GetISOCountryCodeByCountyNameRequest request, System.AsyncCallback callback, object asyncState);
    
    GetISOCountryCodeByCountyNameResponse EndGetISOCountryCodeByCountyName(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.webserviceX.NET/GetCurrencyCode", ReplyAction="*")]
    System.IAsyncResult BeginGetCurrencyCode(GetCurrencyCodeRequest request, System.AsyncCallback callback, object asyncState);
    
    GetCurrencyCodeResponse EndGetCurrencyCode(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.webserviceX.NET/GetCountryByCurrencyCode", ReplyAction="*")]
    System.IAsyncResult BeginGetCountryByCurrencyCode(GetCountryByCurrencyCodeRequest request, System.AsyncCallback callback, object asyncState);
    
    GetCountryByCurrencyCodeResponse EndGetCountryByCurrencyCode(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.webserviceX.NET/GetCurrencies", ReplyAction="*")]
    System.IAsyncResult BeginGetCurrencies(GetCurrenciesRequest request, System.AsyncCallback callback, object asyncState);
    
    GetCurrenciesResponse EndGetCurrencies(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.webserviceX.NET/GetCurrencyByCountry", ReplyAction="*")]
    System.IAsyncResult BeginGetCurrencyByCountry(GetCurrencyByCountryRequest request, System.AsyncCallback callback, object asyncState);
    
    GetCurrencyByCountryResponse EndGetCurrencyByCountry(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.webserviceX.NET/GetGMTbyCountry", ReplyAction="*")]
    System.IAsyncResult BeginGetGMTbyCountry(GetGMTbyCountryRequest request, System.AsyncCallback callback, object asyncState);
    
    GetGMTbyCountryResponse EndGetGMTbyCountry(System.IAsyncResult result);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetCountryByCountryCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCountryCode", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetCountryByCountryCodeRequestBody Body;
    
    public GetCountryByCountryCodeRequest()
    {
    }
    
    public GetCountryByCountryCodeRequest(GetCountryByCountryCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
public partial class GetCountryByCountryCodeRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CountryCode;
    
    public GetCountryByCountryCodeRequestBody()
    {
    }
    
    public GetCountryByCountryCodeRequestBody(string CountryCode)
    {
        this.CountryCode = CountryCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetCountryByCountryCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCountryCodeResponse", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetCountryByCountryCodeResponseBody Body;
    
    public GetCountryByCountryCodeResponse()
    {
    }
    
    public GetCountryByCountryCodeResponse(GetCountryByCountryCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
public partial class GetCountryByCountryCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetCountryByCountryCodeResult;
    
    public GetCountryByCountryCodeResponseBody()
    {
    }
    
    public GetCountryByCountryCodeResponseBody(string GetCountryByCountryCodeResult)
    {
        this.GetCountryByCountryCodeResult = GetCountryByCountryCodeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetISDRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetISD", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetISDRequestBody Body;
    
    public GetISDRequest()
    {
    }
    
    public GetISDRequest(GetISDRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
public partial class GetISDRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CountryName;
    
    public GetISDRequestBody()
    {
    }
    
    public GetISDRequestBody(string CountryName)
    {
        this.CountryName = CountryName;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetISDResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetISDResponse", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetISDResponseBody Body;
    
    public GetISDResponse()
    {
    }
    
    public GetISDResponse(GetISDResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
public partial class GetISDResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetISDResult;
    
    public GetISDResponseBody()
    {
    }
    
    public GetISDResponseBody(string GetISDResult)
    {
        this.GetISDResult = GetISDResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetCountriesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountries", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetCountriesRequestBody Body;
    
    public GetCountriesRequest()
    {
    }
    
    public GetCountriesRequest(GetCountriesRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class GetCountriesRequestBody
{
    
    public GetCountriesRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetCountriesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountriesResponse", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetCountriesResponseBody Body;
    
    public GetCountriesResponse()
    {
    }
    
    public GetCountriesResponse(GetCountriesResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
public partial class GetCountriesResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetCountriesResult;
    
    public GetCountriesResponseBody()
    {
    }
    
    public GetCountriesResponseBody(string GetCountriesResult)
    {
        this.GetCountriesResult = GetCountriesResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetCurrencyCodeByCurrencyNameRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyCodeByCurrencyName", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetCurrencyCodeByCurrencyNameRequestBody Body;
    
    public GetCurrencyCodeByCurrencyNameRequest()
    {
    }
    
    public GetCurrencyCodeByCurrencyNameRequest(GetCurrencyCodeByCurrencyNameRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
public partial class GetCurrencyCodeByCurrencyNameRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CurrencyName;
    
    public GetCurrencyCodeByCurrencyNameRequestBody()
    {
    }
    
    public GetCurrencyCodeByCurrencyNameRequestBody(string CurrencyName)
    {
        this.CurrencyName = CurrencyName;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetCurrencyCodeByCurrencyNameResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyCodeByCurrencyNameResponse", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetCurrencyCodeByCurrencyNameResponseBody Body;
    
    public GetCurrencyCodeByCurrencyNameResponse()
    {
    }
    
    public GetCurrencyCodeByCurrencyNameResponse(GetCurrencyCodeByCurrencyNameResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
public partial class GetCurrencyCodeByCurrencyNameResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetCurrencyCodeByCurrencyNameResult;
    
    public GetCurrencyCodeByCurrencyNameResponseBody()
    {
    }
    
    public GetCurrencyCodeByCurrencyNameResponseBody(string GetCurrencyCodeByCurrencyNameResult)
    {
        this.GetCurrencyCodeByCurrencyNameResult = GetCurrencyCodeByCurrencyNameResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetISOCountryCodeByCountyNameRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetISOCountryCodeByCountyName", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetISOCountryCodeByCountyNameRequestBody Body;
    
    public GetISOCountryCodeByCountyNameRequest()
    {
    }
    
    public GetISOCountryCodeByCountyNameRequest(GetISOCountryCodeByCountyNameRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
public partial class GetISOCountryCodeByCountyNameRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CountryName;
    
    public GetISOCountryCodeByCountyNameRequestBody()
    {
    }
    
    public GetISOCountryCodeByCountyNameRequestBody(string CountryName)
    {
        this.CountryName = CountryName;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetISOCountryCodeByCountyNameResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetISOCountryCodeByCountyNameResponse", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetISOCountryCodeByCountyNameResponseBody Body;
    
    public GetISOCountryCodeByCountyNameResponse()
    {
    }
    
    public GetISOCountryCodeByCountyNameResponse(GetISOCountryCodeByCountyNameResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
public partial class GetISOCountryCodeByCountyNameResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetISOCountryCodeByCountyNameResult;
    
    public GetISOCountryCodeByCountyNameResponseBody()
    {
    }
    
    public GetISOCountryCodeByCountyNameResponseBody(string GetISOCountryCodeByCountyNameResult)
    {
        this.GetISOCountryCodeByCountyNameResult = GetISOCountryCodeByCountyNameResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetCurrencyCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyCode", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetCurrencyCodeRequestBody Body;
    
    public GetCurrencyCodeRequest()
    {
    }
    
    public GetCurrencyCodeRequest(GetCurrencyCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class GetCurrencyCodeRequestBody
{
    
    public GetCurrencyCodeRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetCurrencyCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyCodeResponse", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetCurrencyCodeResponseBody Body;
    
    public GetCurrencyCodeResponse()
    {
    }
    
    public GetCurrencyCodeResponse(GetCurrencyCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
public partial class GetCurrencyCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetCurrencyCodeResult;
    
    public GetCurrencyCodeResponseBody()
    {
    }
    
    public GetCurrencyCodeResponseBody(string GetCurrencyCodeResult)
    {
        this.GetCurrencyCodeResult = GetCurrencyCodeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetCountryByCurrencyCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCurrencyCode", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetCountryByCurrencyCodeRequestBody Body;
    
    public GetCountryByCurrencyCodeRequest()
    {
    }
    
    public GetCountryByCurrencyCodeRequest(GetCountryByCurrencyCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
public partial class GetCountryByCurrencyCodeRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CurrencyCode;
    
    public GetCountryByCurrencyCodeRequestBody()
    {
    }
    
    public GetCountryByCurrencyCodeRequestBody(string CurrencyCode)
    {
        this.CurrencyCode = CurrencyCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetCountryByCurrencyCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCurrencyCodeResponse", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetCountryByCurrencyCodeResponseBody Body;
    
    public GetCountryByCurrencyCodeResponse()
    {
    }
    
    public GetCountryByCurrencyCodeResponse(GetCountryByCurrencyCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
public partial class GetCountryByCurrencyCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetCountryByCurrencyCodeResult;
    
    public GetCountryByCurrencyCodeResponseBody()
    {
    }
    
    public GetCountryByCurrencyCodeResponseBody(string GetCountryByCurrencyCodeResult)
    {
        this.GetCountryByCurrencyCodeResult = GetCountryByCurrencyCodeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetCurrenciesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencies", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetCurrenciesRequestBody Body;
    
    public GetCurrenciesRequest()
    {
    }
    
    public GetCurrenciesRequest(GetCurrenciesRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class GetCurrenciesRequestBody
{
    
    public GetCurrenciesRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetCurrenciesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrenciesResponse", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetCurrenciesResponseBody Body;
    
    public GetCurrenciesResponse()
    {
    }
    
    public GetCurrenciesResponse(GetCurrenciesResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
public partial class GetCurrenciesResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetCurrenciesResult;
    
    public GetCurrenciesResponseBody()
    {
    }
    
    public GetCurrenciesResponseBody(string GetCurrenciesResult)
    {
        this.GetCurrenciesResult = GetCurrenciesResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetCurrencyByCountryRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyByCountry", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetCurrencyByCountryRequestBody Body;
    
    public GetCurrencyByCountryRequest()
    {
    }
    
    public GetCurrencyByCountryRequest(GetCurrencyByCountryRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
public partial class GetCurrencyByCountryRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CountryName;
    
    public GetCurrencyByCountryRequestBody()
    {
    }
    
    public GetCurrencyByCountryRequestBody(string CountryName)
    {
        this.CountryName = CountryName;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetCurrencyByCountryResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyByCountryResponse", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetCurrencyByCountryResponseBody Body;
    
    public GetCurrencyByCountryResponse()
    {
    }
    
    public GetCurrencyByCountryResponse(GetCurrencyByCountryResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
public partial class GetCurrencyByCountryResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetCurrencyByCountryResult;
    
    public GetCurrencyByCountryResponseBody()
    {
    }
    
    public GetCurrencyByCountryResponseBody(string GetCurrencyByCountryResult)
    {
        this.GetCurrencyByCountryResult = GetCurrencyByCountryResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetGMTbyCountryRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGMTbyCountry", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetGMTbyCountryRequestBody Body;
    
    public GetGMTbyCountryRequest()
    {
    }
    
    public GetGMTbyCountryRequest(GetGMTbyCountryRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
public partial class GetGMTbyCountryRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CountryName;
    
    public GetGMTbyCountryRequestBody()
    {
    }
    
    public GetGMTbyCountryRequestBody(string CountryName)
    {
        this.CountryName = CountryName;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetGMTbyCountryResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGMTbyCountryResponse", Namespace="http://www.webserviceX.NET", Order=0)]
    public GetGMTbyCountryResponseBody Body;
    
    public GetGMTbyCountryResponse()
    {
    }
    
    public GetGMTbyCountryResponse(GetGMTbyCountryResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.webserviceX.NET")]
public partial class GetGMTbyCountryResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GetGMTbyCountryResult;
    
    public GetGMTbyCountryResponseBody()
    {
    }
    
    public GetGMTbyCountryResponseBody(string GetGMTbyCountryResult)
    {
        this.GetGMTbyCountryResult = GetGMTbyCountryResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface countrySoapChannel : countrySoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetCountryByCountryCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetCountryByCountryCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetISDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetISDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetCountriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetCountriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetCurrencyCodeByCurrencyNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetCurrencyCodeByCurrencyNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetISOCountryCodeByCountyNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetISOCountryCodeByCountyNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetCurrencyCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetCurrencyCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetCountryByCurrencyCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetCountryByCurrencyCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetCurrenciesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetCurrenciesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetCurrencyByCountryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetCurrencyByCountryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetGMTbyCountryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetGMTbyCountryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class countrySoapClient : System.ServiceModel.ClientBase<countrySoap>, countrySoap
{
    
    private BeginOperationDelegate onBeginGetCountryByCountryCodeDelegate;
    
    private EndOperationDelegate onEndGetCountryByCountryCodeDelegate;
    
    private System.Threading.SendOrPostCallback onGetCountryByCountryCodeCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetISDDelegate;
    
    private EndOperationDelegate onEndGetISDDelegate;
    
    private System.Threading.SendOrPostCallback onGetISDCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetCountriesDelegate;
    
    private EndOperationDelegate onEndGetCountriesDelegate;
    
    private System.Threading.SendOrPostCallback onGetCountriesCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetCurrencyCodeByCurrencyNameDelegate;
    
    private EndOperationDelegate onEndGetCurrencyCodeByCurrencyNameDelegate;
    
    private System.Threading.SendOrPostCallback onGetCurrencyCodeByCurrencyNameCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetISOCountryCodeByCountyNameDelegate;
    
    private EndOperationDelegate onEndGetISOCountryCodeByCountyNameDelegate;
    
    private System.Threading.SendOrPostCallback onGetISOCountryCodeByCountyNameCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetCurrencyCodeDelegate;
    
    private EndOperationDelegate onEndGetCurrencyCodeDelegate;
    
    private System.Threading.SendOrPostCallback onGetCurrencyCodeCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetCountryByCurrencyCodeDelegate;
    
    private EndOperationDelegate onEndGetCountryByCurrencyCodeDelegate;
    
    private System.Threading.SendOrPostCallback onGetCountryByCurrencyCodeCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetCurrenciesDelegate;
    
    private EndOperationDelegate onEndGetCurrenciesDelegate;
    
    private System.Threading.SendOrPostCallback onGetCurrenciesCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetCurrencyByCountryDelegate;
    
    private EndOperationDelegate onEndGetCurrencyByCountryDelegate;
    
    private System.Threading.SendOrPostCallback onGetCurrencyByCountryCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetGMTbyCountryDelegate;
    
    private EndOperationDelegate onEndGetGMTbyCountryDelegate;
    
    private System.Threading.SendOrPostCallback onGetGMTbyCountryCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public countrySoapClient()
    {
    }
    
    public countrySoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public countrySoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public countrySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public countrySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<GetCountryByCountryCodeCompletedEventArgs> GetCountryByCountryCodeCompleted;
    
    public event System.EventHandler<GetISDCompletedEventArgs> GetISDCompleted;
    
    public event System.EventHandler<GetCountriesCompletedEventArgs> GetCountriesCompleted;
    
    public event System.EventHandler<GetCurrencyCodeByCurrencyNameCompletedEventArgs> GetCurrencyCodeByCurrencyNameCompleted;
    
    public event System.EventHandler<GetISOCountryCodeByCountyNameCompletedEventArgs> GetISOCountryCodeByCountyNameCompleted;
    
    public event System.EventHandler<GetCurrencyCodeCompletedEventArgs> GetCurrencyCodeCompleted;
    
    public event System.EventHandler<GetCountryByCurrencyCodeCompletedEventArgs> GetCountryByCurrencyCodeCompleted;
    
    public event System.EventHandler<GetCurrenciesCompletedEventArgs> GetCurrenciesCompleted;
    
    public event System.EventHandler<GetCurrencyByCountryCompletedEventArgs> GetCurrencyByCountryCompleted;
    
    public event System.EventHandler<GetGMTbyCountryCompletedEventArgs> GetGMTbyCountryCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult countrySoap.BeginGetCountryByCountryCode(GetCountryByCountryCodeRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetCountryByCountryCode(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetCountryByCountryCode(string CountryCode, System.AsyncCallback callback, object asyncState)
    {
        GetCountryByCountryCodeRequest inValue = new GetCountryByCountryCodeRequest();
        inValue.Body = new GetCountryByCountryCodeRequestBody();
        inValue.Body.CountryCode = CountryCode;
        return ((countrySoap)(this)).BeginGetCountryByCountryCode(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetCountryByCountryCodeResponse countrySoap.EndGetCountryByCountryCode(System.IAsyncResult result)
    {
        return base.Channel.EndGetCountryByCountryCode(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private string EndGetCountryByCountryCode(System.IAsyncResult result)
    {
        GetCountryByCountryCodeResponse retVal = ((countrySoap)(this)).EndGetCountryByCountryCode(result);
        return retVal.Body.GetCountryByCountryCodeResult;
    }
    
    private System.IAsyncResult OnBeginGetCountryByCountryCode(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string CountryCode = ((string)(inValues[0]));
        return this.BeginGetCountryByCountryCode(CountryCode, callback, asyncState);
    }
    
    private object[] OnEndGetCountryByCountryCode(System.IAsyncResult result)
    {
        string retVal = this.EndGetCountryByCountryCode(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetCountryByCountryCodeCompleted(object state)
    {
        if ((this.GetCountryByCountryCodeCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetCountryByCountryCodeCompleted(this, new GetCountryByCountryCodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetCountryByCountryCodeAsync(string CountryCode)
    {
        this.GetCountryByCountryCodeAsync(CountryCode, null);
    }
    
    public void GetCountryByCountryCodeAsync(string CountryCode, object userState)
    {
        if ((this.onBeginGetCountryByCountryCodeDelegate == null))
        {
            this.onBeginGetCountryByCountryCodeDelegate = new BeginOperationDelegate(this.OnBeginGetCountryByCountryCode);
        }
        if ((this.onEndGetCountryByCountryCodeDelegate == null))
        {
            this.onEndGetCountryByCountryCodeDelegate = new EndOperationDelegate(this.OnEndGetCountryByCountryCode);
        }
        if ((this.onGetCountryByCountryCodeCompletedDelegate == null))
        {
            this.onGetCountryByCountryCodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCountryByCountryCodeCompleted);
        }
        base.InvokeAsync(this.onBeginGetCountryByCountryCodeDelegate, new object[] {
                    CountryCode}, this.onEndGetCountryByCountryCodeDelegate, this.onGetCountryByCountryCodeCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult countrySoap.BeginGetISD(GetISDRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetISD(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetISD(string CountryName, System.AsyncCallback callback, object asyncState)
    {
        GetISDRequest inValue = new GetISDRequest();
        inValue.Body = new GetISDRequestBody();
        inValue.Body.CountryName = CountryName;
        return ((countrySoap)(this)).BeginGetISD(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetISDResponse countrySoap.EndGetISD(System.IAsyncResult result)
    {
        return base.Channel.EndGetISD(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private string EndGetISD(System.IAsyncResult result)
    {
        GetISDResponse retVal = ((countrySoap)(this)).EndGetISD(result);
        return retVal.Body.GetISDResult;
    }
    
    private System.IAsyncResult OnBeginGetISD(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string CountryName = ((string)(inValues[0]));
        return this.BeginGetISD(CountryName, callback, asyncState);
    }
    
    private object[] OnEndGetISD(System.IAsyncResult result)
    {
        string retVal = this.EndGetISD(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetISDCompleted(object state)
    {
        if ((this.GetISDCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetISDCompleted(this, new GetISDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetISDAsync(string CountryName)
    {
        this.GetISDAsync(CountryName, null);
    }
    
    public void GetISDAsync(string CountryName, object userState)
    {
        if ((this.onBeginGetISDDelegate == null))
        {
            this.onBeginGetISDDelegate = new BeginOperationDelegate(this.OnBeginGetISD);
        }
        if ((this.onEndGetISDDelegate == null))
        {
            this.onEndGetISDDelegate = new EndOperationDelegate(this.OnEndGetISD);
        }
        if ((this.onGetISDCompletedDelegate == null))
        {
            this.onGetISDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetISDCompleted);
        }
        base.InvokeAsync(this.onBeginGetISDDelegate, new object[] {
                    CountryName}, this.onEndGetISDDelegate, this.onGetISDCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult countrySoap.BeginGetCountries(GetCountriesRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetCountries(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetCountries(System.AsyncCallback callback, object asyncState)
    {
        GetCountriesRequest inValue = new GetCountriesRequest();
        inValue.Body = new GetCountriesRequestBody();
        return ((countrySoap)(this)).BeginGetCountries(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetCountriesResponse countrySoap.EndGetCountries(System.IAsyncResult result)
    {
        return base.Channel.EndGetCountries(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private string EndGetCountries(System.IAsyncResult result)
    {
        GetCountriesResponse retVal = ((countrySoap)(this)).EndGetCountries(result);
        return retVal.Body.GetCountriesResult;
    }
    
    private System.IAsyncResult OnBeginGetCountries(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginGetCountries(callback, asyncState);
    }
    
    private object[] OnEndGetCountries(System.IAsyncResult result)
    {
        string retVal = this.EndGetCountries(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetCountriesCompleted(object state)
    {
        if ((this.GetCountriesCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetCountriesCompleted(this, new GetCountriesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetCountriesAsync()
    {
        this.GetCountriesAsync(null);
    }
    
    public void GetCountriesAsync(object userState)
    {
        if ((this.onBeginGetCountriesDelegate == null))
        {
            this.onBeginGetCountriesDelegate = new BeginOperationDelegate(this.OnBeginGetCountries);
        }
        if ((this.onEndGetCountriesDelegate == null))
        {
            this.onEndGetCountriesDelegate = new EndOperationDelegate(this.OnEndGetCountries);
        }
        if ((this.onGetCountriesCompletedDelegate == null))
        {
            this.onGetCountriesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCountriesCompleted);
        }
        base.InvokeAsync(this.onBeginGetCountriesDelegate, null, this.onEndGetCountriesDelegate, this.onGetCountriesCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult countrySoap.BeginGetCurrencyCodeByCurrencyName(GetCurrencyCodeByCurrencyNameRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetCurrencyCodeByCurrencyName(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetCurrencyCodeByCurrencyName(string CurrencyName, System.AsyncCallback callback, object asyncState)
    {
        GetCurrencyCodeByCurrencyNameRequest inValue = new GetCurrencyCodeByCurrencyNameRequest();
        inValue.Body = new GetCurrencyCodeByCurrencyNameRequestBody();
        inValue.Body.CurrencyName = CurrencyName;
        return ((countrySoap)(this)).BeginGetCurrencyCodeByCurrencyName(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetCurrencyCodeByCurrencyNameResponse countrySoap.EndGetCurrencyCodeByCurrencyName(System.IAsyncResult result)
    {
        return base.Channel.EndGetCurrencyCodeByCurrencyName(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private string EndGetCurrencyCodeByCurrencyName(System.IAsyncResult result)
    {
        GetCurrencyCodeByCurrencyNameResponse retVal = ((countrySoap)(this)).EndGetCurrencyCodeByCurrencyName(result);
        return retVal.Body.GetCurrencyCodeByCurrencyNameResult;
    }
    
    private System.IAsyncResult OnBeginGetCurrencyCodeByCurrencyName(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string CurrencyName = ((string)(inValues[0]));
        return this.BeginGetCurrencyCodeByCurrencyName(CurrencyName, callback, asyncState);
    }
    
    private object[] OnEndGetCurrencyCodeByCurrencyName(System.IAsyncResult result)
    {
        string retVal = this.EndGetCurrencyCodeByCurrencyName(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetCurrencyCodeByCurrencyNameCompleted(object state)
    {
        if ((this.GetCurrencyCodeByCurrencyNameCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetCurrencyCodeByCurrencyNameCompleted(this, new GetCurrencyCodeByCurrencyNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetCurrencyCodeByCurrencyNameAsync(string CurrencyName)
    {
        this.GetCurrencyCodeByCurrencyNameAsync(CurrencyName, null);
    }
    
    public void GetCurrencyCodeByCurrencyNameAsync(string CurrencyName, object userState)
    {
        if ((this.onBeginGetCurrencyCodeByCurrencyNameDelegate == null))
        {
            this.onBeginGetCurrencyCodeByCurrencyNameDelegate = new BeginOperationDelegate(this.OnBeginGetCurrencyCodeByCurrencyName);
        }
        if ((this.onEndGetCurrencyCodeByCurrencyNameDelegate == null))
        {
            this.onEndGetCurrencyCodeByCurrencyNameDelegate = new EndOperationDelegate(this.OnEndGetCurrencyCodeByCurrencyName);
        }
        if ((this.onGetCurrencyCodeByCurrencyNameCompletedDelegate == null))
        {
            this.onGetCurrencyCodeByCurrencyNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCurrencyCodeByCurrencyNameCompleted);
        }
        base.InvokeAsync(this.onBeginGetCurrencyCodeByCurrencyNameDelegate, new object[] {
                    CurrencyName}, this.onEndGetCurrencyCodeByCurrencyNameDelegate, this.onGetCurrencyCodeByCurrencyNameCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult countrySoap.BeginGetISOCountryCodeByCountyName(GetISOCountryCodeByCountyNameRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetISOCountryCodeByCountyName(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetISOCountryCodeByCountyName(string CountryName, System.AsyncCallback callback, object asyncState)
    {
        GetISOCountryCodeByCountyNameRequest inValue = new GetISOCountryCodeByCountyNameRequest();
        inValue.Body = new GetISOCountryCodeByCountyNameRequestBody();
        inValue.Body.CountryName = CountryName;
        return ((countrySoap)(this)).BeginGetISOCountryCodeByCountyName(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetISOCountryCodeByCountyNameResponse countrySoap.EndGetISOCountryCodeByCountyName(System.IAsyncResult result)
    {
        return base.Channel.EndGetISOCountryCodeByCountyName(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private string EndGetISOCountryCodeByCountyName(System.IAsyncResult result)
    {
        GetISOCountryCodeByCountyNameResponse retVal = ((countrySoap)(this)).EndGetISOCountryCodeByCountyName(result);
        return retVal.Body.GetISOCountryCodeByCountyNameResult;
    }
    
    private System.IAsyncResult OnBeginGetISOCountryCodeByCountyName(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string CountryName = ((string)(inValues[0]));
        return this.BeginGetISOCountryCodeByCountyName(CountryName, callback, asyncState);
    }
    
    private object[] OnEndGetISOCountryCodeByCountyName(System.IAsyncResult result)
    {
        string retVal = this.EndGetISOCountryCodeByCountyName(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetISOCountryCodeByCountyNameCompleted(object state)
    {
        if ((this.GetISOCountryCodeByCountyNameCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetISOCountryCodeByCountyNameCompleted(this, new GetISOCountryCodeByCountyNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetISOCountryCodeByCountyNameAsync(string CountryName)
    {
        this.GetISOCountryCodeByCountyNameAsync(CountryName, null);
    }
    
    public void GetISOCountryCodeByCountyNameAsync(string CountryName, object userState)
    {
        if ((this.onBeginGetISOCountryCodeByCountyNameDelegate == null))
        {
            this.onBeginGetISOCountryCodeByCountyNameDelegate = new BeginOperationDelegate(this.OnBeginGetISOCountryCodeByCountyName);
        }
        if ((this.onEndGetISOCountryCodeByCountyNameDelegate == null))
        {
            this.onEndGetISOCountryCodeByCountyNameDelegate = new EndOperationDelegate(this.OnEndGetISOCountryCodeByCountyName);
        }
        if ((this.onGetISOCountryCodeByCountyNameCompletedDelegate == null))
        {
            this.onGetISOCountryCodeByCountyNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetISOCountryCodeByCountyNameCompleted);
        }
        base.InvokeAsync(this.onBeginGetISOCountryCodeByCountyNameDelegate, new object[] {
                    CountryName}, this.onEndGetISOCountryCodeByCountyNameDelegate, this.onGetISOCountryCodeByCountyNameCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult countrySoap.BeginGetCurrencyCode(GetCurrencyCodeRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetCurrencyCode(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetCurrencyCode(System.AsyncCallback callback, object asyncState)
    {
        GetCurrencyCodeRequest inValue = new GetCurrencyCodeRequest();
        inValue.Body = new GetCurrencyCodeRequestBody();
        return ((countrySoap)(this)).BeginGetCurrencyCode(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetCurrencyCodeResponse countrySoap.EndGetCurrencyCode(System.IAsyncResult result)
    {
        return base.Channel.EndGetCurrencyCode(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private string EndGetCurrencyCode(System.IAsyncResult result)
    {
        GetCurrencyCodeResponse retVal = ((countrySoap)(this)).EndGetCurrencyCode(result);
        return retVal.Body.GetCurrencyCodeResult;
    }
    
    private System.IAsyncResult OnBeginGetCurrencyCode(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginGetCurrencyCode(callback, asyncState);
    }
    
    private object[] OnEndGetCurrencyCode(System.IAsyncResult result)
    {
        string retVal = this.EndGetCurrencyCode(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetCurrencyCodeCompleted(object state)
    {
        if ((this.GetCurrencyCodeCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetCurrencyCodeCompleted(this, new GetCurrencyCodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetCurrencyCodeAsync()
    {
        this.GetCurrencyCodeAsync(null);
    }
    
    public void GetCurrencyCodeAsync(object userState)
    {
        if ((this.onBeginGetCurrencyCodeDelegate == null))
        {
            this.onBeginGetCurrencyCodeDelegate = new BeginOperationDelegate(this.OnBeginGetCurrencyCode);
        }
        if ((this.onEndGetCurrencyCodeDelegate == null))
        {
            this.onEndGetCurrencyCodeDelegate = new EndOperationDelegate(this.OnEndGetCurrencyCode);
        }
        if ((this.onGetCurrencyCodeCompletedDelegate == null))
        {
            this.onGetCurrencyCodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCurrencyCodeCompleted);
        }
        base.InvokeAsync(this.onBeginGetCurrencyCodeDelegate, null, this.onEndGetCurrencyCodeDelegate, this.onGetCurrencyCodeCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult countrySoap.BeginGetCountryByCurrencyCode(GetCountryByCurrencyCodeRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetCountryByCurrencyCode(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetCountryByCurrencyCode(string CurrencyCode, System.AsyncCallback callback, object asyncState)
    {
        GetCountryByCurrencyCodeRequest inValue = new GetCountryByCurrencyCodeRequest();
        inValue.Body = new GetCountryByCurrencyCodeRequestBody();
        inValue.Body.CurrencyCode = CurrencyCode;
        return ((countrySoap)(this)).BeginGetCountryByCurrencyCode(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetCountryByCurrencyCodeResponse countrySoap.EndGetCountryByCurrencyCode(System.IAsyncResult result)
    {
        return base.Channel.EndGetCountryByCurrencyCode(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private string EndGetCountryByCurrencyCode(System.IAsyncResult result)
    {
        GetCountryByCurrencyCodeResponse retVal = ((countrySoap)(this)).EndGetCountryByCurrencyCode(result);
        return retVal.Body.GetCountryByCurrencyCodeResult;
    }
    
    private System.IAsyncResult OnBeginGetCountryByCurrencyCode(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string CurrencyCode = ((string)(inValues[0]));
        return this.BeginGetCountryByCurrencyCode(CurrencyCode, callback, asyncState);
    }
    
    private object[] OnEndGetCountryByCurrencyCode(System.IAsyncResult result)
    {
        string retVal = this.EndGetCountryByCurrencyCode(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetCountryByCurrencyCodeCompleted(object state)
    {
        if ((this.GetCountryByCurrencyCodeCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetCountryByCurrencyCodeCompleted(this, new GetCountryByCurrencyCodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetCountryByCurrencyCodeAsync(string CurrencyCode)
    {
        this.GetCountryByCurrencyCodeAsync(CurrencyCode, null);
    }
    
    public void GetCountryByCurrencyCodeAsync(string CurrencyCode, object userState)
    {
        if ((this.onBeginGetCountryByCurrencyCodeDelegate == null))
        {
            this.onBeginGetCountryByCurrencyCodeDelegate = new BeginOperationDelegate(this.OnBeginGetCountryByCurrencyCode);
        }
        if ((this.onEndGetCountryByCurrencyCodeDelegate == null))
        {
            this.onEndGetCountryByCurrencyCodeDelegate = new EndOperationDelegate(this.OnEndGetCountryByCurrencyCode);
        }
        if ((this.onGetCountryByCurrencyCodeCompletedDelegate == null))
        {
            this.onGetCountryByCurrencyCodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCountryByCurrencyCodeCompleted);
        }
        base.InvokeAsync(this.onBeginGetCountryByCurrencyCodeDelegate, new object[] {
                    CurrencyCode}, this.onEndGetCountryByCurrencyCodeDelegate, this.onGetCountryByCurrencyCodeCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult countrySoap.BeginGetCurrencies(GetCurrenciesRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetCurrencies(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetCurrencies(System.AsyncCallback callback, object asyncState)
    {
        GetCurrenciesRequest inValue = new GetCurrenciesRequest();
        inValue.Body = new GetCurrenciesRequestBody();
        return ((countrySoap)(this)).BeginGetCurrencies(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetCurrenciesResponse countrySoap.EndGetCurrencies(System.IAsyncResult result)
    {
        return base.Channel.EndGetCurrencies(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private string EndGetCurrencies(System.IAsyncResult result)
    {
        GetCurrenciesResponse retVal = ((countrySoap)(this)).EndGetCurrencies(result);
        return retVal.Body.GetCurrenciesResult;
    }
    
    private System.IAsyncResult OnBeginGetCurrencies(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginGetCurrencies(callback, asyncState);
    }
    
    private object[] OnEndGetCurrencies(System.IAsyncResult result)
    {
        string retVal = this.EndGetCurrencies(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetCurrenciesCompleted(object state)
    {
        if ((this.GetCurrenciesCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetCurrenciesCompleted(this, new GetCurrenciesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetCurrenciesAsync()
    {
        this.GetCurrenciesAsync(null);
    }
    
    public void GetCurrenciesAsync(object userState)
    {
        if ((this.onBeginGetCurrenciesDelegate == null))
        {
            this.onBeginGetCurrenciesDelegate = new BeginOperationDelegate(this.OnBeginGetCurrencies);
        }
        if ((this.onEndGetCurrenciesDelegate == null))
        {
            this.onEndGetCurrenciesDelegate = new EndOperationDelegate(this.OnEndGetCurrencies);
        }
        if ((this.onGetCurrenciesCompletedDelegate == null))
        {
            this.onGetCurrenciesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCurrenciesCompleted);
        }
        base.InvokeAsync(this.onBeginGetCurrenciesDelegate, null, this.onEndGetCurrenciesDelegate, this.onGetCurrenciesCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult countrySoap.BeginGetCurrencyByCountry(GetCurrencyByCountryRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetCurrencyByCountry(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetCurrencyByCountry(string CountryName, System.AsyncCallback callback, object asyncState)
    {
        GetCurrencyByCountryRequest inValue = new GetCurrencyByCountryRequest();
        inValue.Body = new GetCurrencyByCountryRequestBody();
        inValue.Body.CountryName = CountryName;
        return ((countrySoap)(this)).BeginGetCurrencyByCountry(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetCurrencyByCountryResponse countrySoap.EndGetCurrencyByCountry(System.IAsyncResult result)
    {
        return base.Channel.EndGetCurrencyByCountry(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private string EndGetCurrencyByCountry(System.IAsyncResult result)
    {
        GetCurrencyByCountryResponse retVal = ((countrySoap)(this)).EndGetCurrencyByCountry(result);
        return retVal.Body.GetCurrencyByCountryResult;
    }
    
    private System.IAsyncResult OnBeginGetCurrencyByCountry(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string CountryName = ((string)(inValues[0]));
        return this.BeginGetCurrencyByCountry(CountryName, callback, asyncState);
    }
    
    private object[] OnEndGetCurrencyByCountry(System.IAsyncResult result)
    {
        string retVal = this.EndGetCurrencyByCountry(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetCurrencyByCountryCompleted(object state)
    {
        if ((this.GetCurrencyByCountryCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetCurrencyByCountryCompleted(this, new GetCurrencyByCountryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetCurrencyByCountryAsync(string CountryName)
    {
        this.GetCurrencyByCountryAsync(CountryName, null);
    }
    
    public void GetCurrencyByCountryAsync(string CountryName, object userState)
    {
        if ((this.onBeginGetCurrencyByCountryDelegate == null))
        {
            this.onBeginGetCurrencyByCountryDelegate = new BeginOperationDelegate(this.OnBeginGetCurrencyByCountry);
        }
        if ((this.onEndGetCurrencyByCountryDelegate == null))
        {
            this.onEndGetCurrencyByCountryDelegate = new EndOperationDelegate(this.OnEndGetCurrencyByCountry);
        }
        if ((this.onGetCurrencyByCountryCompletedDelegate == null))
        {
            this.onGetCurrencyByCountryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCurrencyByCountryCompleted);
        }
        base.InvokeAsync(this.onBeginGetCurrencyByCountryDelegate, new object[] {
                    CountryName}, this.onEndGetCurrencyByCountryDelegate, this.onGetCurrencyByCountryCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult countrySoap.BeginGetGMTbyCountry(GetGMTbyCountryRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetGMTbyCountry(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginGetGMTbyCountry(string CountryName, System.AsyncCallback callback, object asyncState)
    {
        GetGMTbyCountryRequest inValue = new GetGMTbyCountryRequest();
        inValue.Body = new GetGMTbyCountryRequestBody();
        inValue.Body.CountryName = CountryName;
        return ((countrySoap)(this)).BeginGetGMTbyCountry(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetGMTbyCountryResponse countrySoap.EndGetGMTbyCountry(System.IAsyncResult result)
    {
        return base.Channel.EndGetGMTbyCountry(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private string EndGetGMTbyCountry(System.IAsyncResult result)
    {
        GetGMTbyCountryResponse retVal = ((countrySoap)(this)).EndGetGMTbyCountry(result);
        return retVal.Body.GetGMTbyCountryResult;
    }
    
    private System.IAsyncResult OnBeginGetGMTbyCountry(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string CountryName = ((string)(inValues[0]));
        return this.BeginGetGMTbyCountry(CountryName, callback, asyncState);
    }
    
    private object[] OnEndGetGMTbyCountry(System.IAsyncResult result)
    {
        string retVal = this.EndGetGMTbyCountry(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetGMTbyCountryCompleted(object state)
    {
        if ((this.GetGMTbyCountryCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetGMTbyCountryCompleted(this, new GetGMTbyCountryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetGMTbyCountryAsync(string CountryName)
    {
        this.GetGMTbyCountryAsync(CountryName, null);
    }
    
    public void GetGMTbyCountryAsync(string CountryName, object userState)
    {
        if ((this.onBeginGetGMTbyCountryDelegate == null))
        {
            this.onBeginGetGMTbyCountryDelegate = new BeginOperationDelegate(this.OnBeginGetGMTbyCountry);
        }
        if ((this.onEndGetGMTbyCountryDelegate == null))
        {
            this.onEndGetGMTbyCountryDelegate = new EndOperationDelegate(this.OnEndGetGMTbyCountry);
        }
        if ((this.onGetGMTbyCountryCompletedDelegate == null))
        {
            this.onGetGMTbyCountryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetGMTbyCountryCompleted);
        }
        base.InvokeAsync(this.onBeginGetGMTbyCountryDelegate, new object[] {
                    CountryName}, this.onEndGetGMTbyCountryDelegate, this.onGetGMTbyCountryCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override countrySoap CreateChannel()
    {
        return new countrySoapClientChannel(this);
    }
    
    private class countrySoapClientChannel : ChannelBase<countrySoap>, countrySoap
    {
        
        public countrySoapClientChannel(System.ServiceModel.ClientBase<countrySoap> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginGetCountryByCountryCode(GetCountryByCountryCodeRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetCountryByCountryCode", _args, callback, asyncState);
            return _result;
        }
        
        public GetCountryByCountryCodeResponse EndGetCountryByCountryCode(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetCountryByCountryCodeResponse _result = ((GetCountryByCountryCodeResponse)(base.EndInvoke("GetCountryByCountryCode", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetISD(GetISDRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetISD", _args, callback, asyncState);
            return _result;
        }
        
        public GetISDResponse EndGetISD(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetISDResponse _result = ((GetISDResponse)(base.EndInvoke("GetISD", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetCountries(GetCountriesRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetCountries", _args, callback, asyncState);
            return _result;
        }
        
        public GetCountriesResponse EndGetCountries(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetCountriesResponse _result = ((GetCountriesResponse)(base.EndInvoke("GetCountries", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetCurrencyCodeByCurrencyName(GetCurrencyCodeByCurrencyNameRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetCurrencyCodeByCurrencyName", _args, callback, asyncState);
            return _result;
        }
        
        public GetCurrencyCodeByCurrencyNameResponse EndGetCurrencyCodeByCurrencyName(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetCurrencyCodeByCurrencyNameResponse _result = ((GetCurrencyCodeByCurrencyNameResponse)(base.EndInvoke("GetCurrencyCodeByCurrencyName", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetISOCountryCodeByCountyName(GetISOCountryCodeByCountyNameRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetISOCountryCodeByCountyName", _args, callback, asyncState);
            return _result;
        }
        
        public GetISOCountryCodeByCountyNameResponse EndGetISOCountryCodeByCountyName(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetISOCountryCodeByCountyNameResponse _result = ((GetISOCountryCodeByCountyNameResponse)(base.EndInvoke("GetISOCountryCodeByCountyName", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetCurrencyCode(GetCurrencyCodeRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetCurrencyCode", _args, callback, asyncState);
            return _result;
        }
        
        public GetCurrencyCodeResponse EndGetCurrencyCode(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetCurrencyCodeResponse _result = ((GetCurrencyCodeResponse)(base.EndInvoke("GetCurrencyCode", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetCountryByCurrencyCode(GetCountryByCurrencyCodeRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetCountryByCurrencyCode", _args, callback, asyncState);
            return _result;
        }
        
        public GetCountryByCurrencyCodeResponse EndGetCountryByCurrencyCode(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetCountryByCurrencyCodeResponse _result = ((GetCountryByCurrencyCodeResponse)(base.EndInvoke("GetCountryByCurrencyCode", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetCurrencies(GetCurrenciesRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetCurrencies", _args, callback, asyncState);
            return _result;
        }
        
        public GetCurrenciesResponse EndGetCurrencies(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetCurrenciesResponse _result = ((GetCurrenciesResponse)(base.EndInvoke("GetCurrencies", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetCurrencyByCountry(GetCurrencyByCountryRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetCurrencyByCountry", _args, callback, asyncState);
            return _result;
        }
        
        public GetCurrencyByCountryResponse EndGetCurrencyByCountry(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetCurrencyByCountryResponse _result = ((GetCurrencyByCountryResponse)(base.EndInvoke("GetCurrencyByCountry", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetGMTbyCountry(GetGMTbyCountryRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetGMTbyCountry", _args, callback, asyncState);
            return _result;
        }
        
        public GetGMTbyCountryResponse EndGetGMTbyCountry(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            GetGMTbyCountryResponse _result = ((GetGMTbyCountryResponse)(base.EndInvoke("GetGMTbyCountry", _args, result)));
            return _result;
        }
    }
}
